(() => {
'use strict';
const c=document.getElementById('game'),ctx=c.getContext('2d'),$=id=>document.getElementById(id);
const panels=['startPanel','gameOverPanel','pausePanel','shopPanel'];
let W=390,H=844,DPR=1,last=0,state='menu',paused=false;
let speed=118,alt=0,runScrolls=0,best=+(localStorage.ninjaBest||0),bank=+(localStorage.ninjaScrolls||0);
let skin=localStorage.ninjaSkin||'blue',goldUnlocked=localStorage.ninjaGold==='1',objects=[],particles=[],decor=[],wallOff=0,bgOff=0;
let next={enemy:.6,scroll:1.6,shield:11,shuriken:6,raven:9,dragon:22,roof:8,clothes:5};
let shield=false,shieldT=0,dragon=false,dragonT=0,shake=0,revived=false;
const P={side:'left',x:0,y:0,fromX:0,toX:0,t:1,dur:.23,w:58,h:78,inv:0};
const qs=new URLSearchParams(location.search),auto=qs.get('autostart')==='1'||qs.get('autoplay')==='1';
function show(id=''){panels.forEach(p=>$(p).classList.toggle('hidden',p!==id));}
function ww(){return Math.max(52,Math.min(72,W*.145))}
function sx(side){return side==='left'?ww()+P.w*.30:W-ww()-P.w*.30}
function setSide(anim=true){const nx=sx(P.side);if(anim){P.fromX=P.x;P.toX=nx;P.t=0}else P.x=P.fromX=P.toX=nx}
function resize(){const r=c.getBoundingClientRect();DPR=Math.min(devicePixelRatio||1,2);c.width=r.width*DPR;c.height=r.height*DPR;W=r.width;H=r.height;ctx.setTransform(DPR,0,0,DPR,0,0);P.w=Math.max(48,W*.14);P.h=P.w*1.38;P.y=H*.69;setSide(false)}
addEventListener('resize',resize,{passive:true});resize();
function menu(){ $('bestStart').textContent=best+' m';$('bankStart').textContent=bank;refreshShop(); }
function sync(){ $('altitude').textContent=Math.floor(alt);$('scrolls').textContent=runScrolls; }
function resetTimers(){next={enemy:.7,scroll:2,shield:12+Math.random()*5,shuriken:6.5,raven:9.5,dragon:22+Math.random()*8,roof:8,clothes:5}}
function start(){state='playing';paused=false;speed=118;alt=0;runScrolls=0;objects=[];particles=[];decor=[];shield=false;dragon=false;shieldT=dragonT=0;shake=0;revived=false;wallOff=bgOff=0;P.side='left';P.y=H*.69;P.inv=1;setSide(false);resetTimers();show();$('hud').classList.remove('hidden');$('pauseBtn').classList.remove('hidden');sync()}
function over(){if(state!=='playing')return;state='gameover';best=Math.max(best,Math.floor(alt));bank+=runScrolls;localStorage.ninjaBest=best;localStorage.ninjaScrolls=bank;$('finalAltitude').textContent=Math.floor(alt);$('hud').classList.add('hidden');$('pauseBtn').classList.add('hidden');$('reviveBtn').classList.toggle('hidden',revived||bank<500);show('gameOverPanel');menu()}
function jump(){if(state!=='playing'||paused||dragon)return;P.side=P.side==='left'?'right':'left';setSide(true);burst(P.x,P.y+P.h*.3,8,'#f4d7b0')}
function togglePause(force){if(state!=='playing')return;paused=force??!paused;show(paused?'pausePanel':'')}
function spawn(type,side='center',y=-80,extra={}){objects.push({type,side,x:extra.x??0,y,vx:extra.vx||0,vy:extra.vy||0,phase:extra.phase||'move',timer:extra.timer||0,rot:Math.random()*6.2,dead:false,...extra})}
function enemy(){spawn(Math.random()<.72?'red':'black',Math.random()<.5?'left':'right',-80)}
function scroll(){spawn('scroll',Math.random()<.5?'left':'right',-70)}
function roof(){spawn('roof',Math.random()<.5?'left':'right',-90)}
function clothes(){decor.push({type:'clothes',y:-100,life:1})}
function shieldSpawn(){spawn('shield','center',-70,{x:W*(.34+Math.random()*.32)})}
function shuriken(){const l=Math.random()<.5;spawn('shuriken','center',H*(.24+Math.random()*.34),{x:l?ww():W-ww(),vx:(l?1:-1)*(155+alt*.012)})}
function raven(){spawn('raven','center',H*.13,{x:W*(.3+Math.random()*.4),phase:'hover',timer:1.05})}
function dragonSpawn(){spawn('dragon','center',-100,{x:W*.5,phase:'descend'})}
function burst(x,y,n,col){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*130,vy:(Math.random()-.7)*130,life:.35+Math.random()*.4,max:.75,size:2+Math.random()*4,col})}
function size(t){switch(t){case'red':case'black':return{w:W*.115,h:W*.16};case'raven':return{w:W*.14,h:W*.095};case'shuriken':return{w:W*.075,h:W*.075};case'scroll':return{w:W*.075,h:W*.075};case'shield':return{w:W*.095,h:W*.095};case'dragon':return{w:W*.19,h:W*.15};case'roof':return{w:W*.19,h:W*.105};default:return{w:50,h:50}}}
function rectP(){return{x:P.x-P.w*.25,y:P.y-P.h*.32,w:P.w*.5,h:P.h*.64}}
function rectO(o){const s=size(o.type);return{x:o.x-s.w*.34,y:o.y-s.h*.34,w:s.w*.68,h:s.h*.68}}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function update(dt){if(state!=='playing'||paused)return;if(P.inv>0)P.inv-=dt;const v=dragon?speed*3.05:speed;wallOff=(wallOff+v*dt)%220;bgOff=(bgOff+v*.035*dt)%H;alt+=v*dt/8.2;if(dragon)alt+=v*dt/9;speed=Math.min(195,118+alt*.019);if(!dragon&&P.t<1){P.t=Math.min(1,P.t+dt/P.dur);const q=1-Math.pow(1-P.t,3);P.x=P.fromX+(P.toX-P.fromX)*q}if(shield&&(shieldT-=dt)<=0)shield=false;if(dragon){dragonT-=dt;P.y=Math.max(H*.38,P.y-dt*40);if(dragonT<=0){dragon=false;P.y=H*.69;P.inv=1;setSide(false)}}Object.keys(next).forEach(k=>next[k]-=dt);if(next.enemy<=0&&!dragon){enemy();next.enemy=Math.max(1.05,2.6-alt/1400)+Math.random()*.65}if(next.scroll<=0){scroll();next.scroll=3+Math.random()*2.6}if(next.shield<=0){shieldSpawn();next.shield=16+Math.random()*12}if(next.shuriken<=0&&alt>65){shuriken();next.shuriken=Math.max(4.7,8.8-alt/700)+Math.random()*3}if(next.raven<=0&&alt>115){raven();next.raven=Math.max(6.5,11-alt/700)+Math.random()*4}if(next.dragon<=0&&alt>200){dragonSpawn();next.dragon=30+Math.random()*22}if(next.roof<=0&&alt>120){roof();next.roof=8+Math.random()*8}if(next.clothes<=0){clothes();next.clothes=11+Math.random()*10}for(const d of decor)d.y+=v*dt;decor=decor.filter(d=>d.y<H+120);for(const o of objects){if(o.dead)continue;if(['red','black','scroll','shield','dragon','roof'].includes(o.type))o.y+=v*dt;if(['red','black','scroll','roof'].includes(o.type)){const s=size(o.type);o.x=o.side==='left'?ww()+s.w*.27:W-ww()-s.w*.27}if(o.type==='shuriken'){o.x+=o.vx*dt;o.rot+=dt*9}if(o.type==='raven'){if(o.phase==='hover'){o.timer-=dt;o.y=H*.14+Math.sin(performance.now()/105)*5;if(o.timer<=0){o.phase='dive';let dx=P.x-o.x,dy=P.y-o.y,L=Math.hypot(dx,dy)||1;o.vx=dx/L*310;o.vy=dy/L*310}}else{o.x+=o.vx*dt;o.y+=o.vy*dt}}if(o.type==='dragon'){if(o.phase==='descend'&&o.y>H*.21){o.phase='hover';o.timer=3.3}else if(o.phase==='hover'){o.timer-=dt;o.y+=Math.sin(performance.now()/130)*.25;if(o.timer<=0)o.dead=true}}if(o.y>H+150||o.x<-140||o.x>W+140)o.dead=true;if(!o.dead&&hit(rectP(),rectO(o))){if(o.type==='scroll'){runScrolls+=100;o.dead=true;burst(o.x,o.y,12,'#ffd24a')}else if(o.type==='shield'){shield=true;shieldT=5;o.dead=true;burst(o.x,o.y,15,'#54ddff')}else if(o.type==='dragon'){dragon=true;dragonT=7;shield=false;o.dead=true;objects.forEach(z=>{if(['red','black','raven','shuriken','roof'].includes(z.type))z.dead=true});burst(P.x,P.y,24,'#ff9d18');shake=.35}else if(['red','black','raven','shuriken','roof'].includes(o.type)){if(dragon){o.dead=true;burst(o.x,o.y,14,'#ff9d18');shake=.15}else if(shield){shield=false;o.dead=true;burst(o.x,o.y,14,'#58e7ff');shake=.12}else if(P.inv<=0){over();break}}}}objects=objects.filter(o=>!o.dead);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-dt);sync()}
function round(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function bg(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#f49a73');g.addColorStop(.45,'#ffd99a');g.addColorStop(1,'#8fa1c8');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.18;for(let i=0;i<8;i++){let y=H*.35+i*H*.1-(bgOff%(H*.1));ctx.fillStyle=i<3?'#a45d62':'#596989';ctx.beginPath();ctx.moveTo(0,y+70);for(let x=0;x<=W;x+=45){ctx.lineTo(x,y+30-Math.abs(Math.sin(x*.03+i))*50)}ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill()}ctx.globalAlpha=1;const py=H*.46;ctx.save();ctx.translate(W/2,py);ctx.globalAlpha=.38;ctx.fillStyle='#533842';for(let i=0;i<3;i++){let yy=-i*34,w=92-i*20;ctx.fillRect(-w*.28,yy-18,w*.56,22);ctx.beginPath();ctx.moveTo(-w/2,yy-18);ctx.lineTo(0,yy-34);ctx.lineTo(w/2,yy-18);ctx.closePath();ctx.fill()}ctx.fillRect(-22,0,44,70);ctx.restore();ctx.globalAlpha=1;}
function walls(){let w=ww();for(const x of [0,W-w]){ctx.fillStyle='#e2b278';ctx.fillRect(x,0,w,H);ctx.fillStyle='#b66c39';for(let y=-220+(wallOff%220);y<H;y+=220){ctx.fillRect(x,y,w,5);ctx.fillStyle='#f0c990';for(let j=0;j<5;j++){ctx.fillRect(x+7+(j%2)*5,y+18+j*37,w-14-(j%2)*10,2)}ctx.fillStyle='#b66c39'}ctx.fillStyle='#664125';ctx.fillRect(x===0?w-7:x,0,7,H);for(let y=-100+(wallOff%100);y<H;y+=100){ctx.fillStyle='#8b532d';let lx=x===0?w-7:x-14;ctx.fillRect(lx,y,18,7);ctx.fillStyle='#c99455';ctx.fillRect(lx+2,y+1,14,3)}}}
function drawClothes(y){ctx.save();ctx.translate(0,y);ctx.strokeStyle='#75451f';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(ww(),5);ctx.quadraticCurveTo(W/2,22,W-ww(),5);ctx.stroke();const cols=['#d62828','#2455ad','#7b2cbf','#31343b','#19a542','#f0eee7','#d4a72c'];for(let i=0;i<7;i++){let x=ww()+18+i*(W-2*ww()-36)/6,hh=18+(i%3)*8;ctx.fillStyle=cols[i];ctx.fillRect(x-8,9+(i%2)*2,16,hh)}ctx.restore()}
function ninja(x,y,col='#1177ff',enemy=false,flip=false){ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.strokeStyle='#10121a';ctx.lineWidth=2;ctx.fillStyle='#171a23';ctx.beginPath();ctx.arc(0,-18,12,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=col;ctx.fillRect(-13,-27,26,8);ctx.beginPath();ctx.moveTo(12,-25);ctx.lineTo(25,-32);ctx.lineTo(18,-20);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(enemy?-4:4,-18,4,2.4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#151821';round(-9,-6,18,23,6);ctx.fill();ctx.fillStyle=col;ctx.fillRect(-11,-8,22,5);ctx.strokeStyle='#10121a';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-5,14);ctx.lineTo(-11,28);ctx.moveTo(5,14);ctx.lineTo(10,28);ctx.moveTo(-8,0);ctx.lineTo(-18,9);ctx.moveTo(8,0);ctx.lineTo(18,8);ctx.stroke();ctx.restore()}
function shuri(x,y,r,rot){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.fillStyle='#2b2e38';ctx.strokeStyle='#d9e2ed';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<8;i++){let a=i*Math.PI/4,rr=i%2?4:r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
function ravenDraw(x,y,flip){ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.fillStyle='#171827';ctx.beginPath();ctx.ellipse(0,0,13,8,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-2,-2);ctx.lineTo(-22,-13);ctx.lineTo(-10,4);ctx.moveTo(2,-2);ctx.lineTo(22,-13);ctx.lineTo(10,4);ctx.fill();ctx.fillStyle='#ffcc55';ctx.beginPath();ctx.moveTo(12,-1);ctx.lineTo(22,2);ctx.lineTo(12,4);ctx.fill();ctx.restore()}
function dragonDraw(x,y,withPlayer=false){ctx.save();ctx.translate(x,y);ctx.fillStyle='#bd2b28';ctx.beginPath();ctx.ellipse(0,5,34,14,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff9c18';ctx.beginPath();ctx.moveTo(-12,0);ctx.lineTo(-32,-28);ctx.lineTo(0,-8);ctx.moveTo(5,0);ctx.lineTo(28,-25);ctx.lineTo(25,6);ctx.fill();ctx.fillStyle='#f04b24';ctx.beginPath();ctx.moveTo(28,3);ctx.lineTo(42,-5);ctx.lineTo(34,10);ctx.fill();ctx.fillStyle='#ffb31a';for(let i=-20;i<18;i+=10){ctx.beginPath();ctx.moveTo(i,-7);ctx.lineTo(i+6,-17);ctx.lineTo(i+10,-6);ctx.fill()}if(withPlayer)ninja(-2,-18,skin==='gold'?'#f4b31a':'#1683ff');ctx.restore()}
function objectDraw(o){const s=size(o.type);if(o.type==='red'||o.type==='black')ninja(o.x,o.y,o.type==='red'?'#d3222d':'#202127',true,o.side==='right');else if(o.type==='raven')ravenDraw(o.x,o.y,o.vx<0);else if(o.type==='shuriken')shuri(o.x,o.y,s.w*.48,o.rot);else if(o.type==='scroll'){ctx.save();ctx.translate(o.x,o.y);ctx.fillStyle='#e9c681';round(-12,-9,24,18,5);ctx.fill();ctx.fillStyle='#bb3434';ctx.fillRect(-12,-2,24,4);ctx.restore()}else if(o.type==='shield'){ctx.strokeStyle='#67e6ff';ctx.lineWidth=4;ctx.fillStyle='#5bdfff33';ctx.beginPath();ctx.arc(o.x,o.y,s.w*.45,0,Math.PI*2);ctx.fill();ctx.stroke()}else if(o.type==='dragon')dragonDraw(o.x,o.y);else if(o.type==='roof'){ctx.save();ctx.translate(o.x,o.y);ctx.fillStyle='#242b43';ctx.beginPath();ctx.moveTo(-s.w/2,0);ctx.lineTo(s.w/2,-5);ctx.lineTo(s.w*.38,10);ctx.lineTo(-s.w*.5,10);ctx.fill();ctx.fillStyle='#b9382d';for(let i=-s.w*.38;i<s.w*.35;i+=9)ctx.fillRect(i,-1,7,8);ctx.restore()}}
function playerDraw(){if(dragon){dragonDraw(W*.5,P.y+Math.sin(performance.now()/90)*5,true);return}ninja(P.x,P.y,skin==='gold'?'#f4b31a':'#1683ff',false,P.side==='right');if(shield){ctx.fillStyle='#5ddfff22';ctx.strokeStyle='#73eaff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(P.x,P.y-2,P.w*.75,0,Math.PI*2);ctx.fill();ctx.stroke()}}
function render(){ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*9,(Math.random()-.5)*9);bg();for(const d of decor)drawClothes(d.y);walls();objects.forEach(objectDraw);playerDraw();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.col;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(dragon){ctx.fillStyle='#ffad1830';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#ffe89d66';for(let i=0;i<8;i++){let x=(i*61+performance.now()*.35)%W;ctx.beginPath();ctx.moveTo(x,H*.2);ctx.lineTo(x-45,H*.85);ctx.stroke()}}ctx.restore()}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}
function refreshShop(){const gb=$('goldSkinBtn');gb.textContent=goldUnlocked?(skin==='gold'?'SELECTED':'SELECT'):'UNLOCK';document.querySelector('[data-skin="gold"]').classList.toggle('active',skin==='gold');document.querySelector('[data-skin="blue"]').classList.toggle('active',skin==='blue')}
$('startBtn').onclick=start;$('retryBtn').onclick=start;$('pauseBtn').onclick=()=>togglePause();$('resumeBtn').onclick=()=>togglePause(false);$('restartBtn').onclick=start;$('shopBtn').onclick=()=>{show('shopPanel');refreshShop()};$('closeShopBtn').onclick=()=>show(state==='gameover'?'gameOverPanel':'startPanel');$('settingsBtn').onclick=()=>alert('Sound and vibration use your device settings.');
$('blueSkinBtn').onclick=()=>{skin='blue';localStorage.ninjaSkin=skin;refreshShop()};$('goldSkinBtn').onclick=()=>{if(!goldUnlocked){if(bank<4000){$('toast').textContent='Need 4,000 Scrolls';$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),1200);return}bank-=4000;goldUnlocked=true;localStorage.ninjaGold='1';localStorage.ninjaScrolls=bank}skin='gold';localStorage.ninjaSkin=skin;menu()};
$('reviveBtn').onclick=()=>{if(revived||bank<500)return;bank-=500;localStorage.ninjaScrolls=bank;revived=true;state='playing';objects=[];P.inv=2;shield=true;shieldT=2;show();$('hud').classList.remove('hidden');$('pauseBtn').classList.remove('hidden')};
c.addEventListener('pointerdown',e=>{e.preventDefault();if(state==='playing'&&!paused)jump()},{passive:false});document.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowLeft'||e.code==='ArrowRight'){e.preventDefault();jump()}});
menu();requestAnimationFrame(loop);if(auto)setTimeout(start,250);
})();
