(() => {
'use strict';
const c=document.getElementById('game'),ctx=c.getContext('2d'),$=id=>document.getElementById(id);
const panels=['startPanel','gameOverPanel','pausePanel','shopPanel'];
let W=390,H=844,DPR=1,last=0,state='menu',paused=false;
let speed=118,alt=0,runScrolls=0,best=+(localStorage.ninjaBest||0),bank=+(localStorage.ninjaScrolls||0);
let skin=localStorage.ninjaSkin||'blue',goldUnlocked=localStorage.ninjaGold==='1',objects=[],particles=[],decor=[],wallOff=0,bgOff=0;
let next={enemy:.6,scroll:1.6,shield:11,shuriken:6,raven:9,dragon:22,roof:8,clothes:5};
let shield=false,shieldT=0,dragon=false,dragonT=0,shake=0,revived=false;
const P={side:'left',x:0,y:0,fromX:0,toX:0,t:1,dur:.23,w:58,h:78,inv:0};
const qs=new URLSearchParams(location.search),auto=qs.get('autostart')==='1'||qs.get('autoplay')==='1';
const ATLAS_BASE='https://raw.githubusercontent.com/alnaimistudio/aippy/main/ninja-climb/assets/';
const A={background:[4,4,253,448],wall:[261,4,95,354],playerBlue:[359,4,134,199],playerGold:[4,456,134,177],enemyRed:[142,456,118,171],enemyBlack:[264,456,118,160],dragonBlue:[387,456,171,158],dragonGold:[4,637,205,157],dragon:[213,637,150,146],roof:[367,637,174,112],raven:[4,798,150,98],shield:[158,798,103,97],shuriken:[264,798,87,86],scroll:[355,798,87,84],clothes:[4,900,250,83]};
const atlas=new Image();let atlasReady=false,atlasError=false;window.__NINJA_ART_READY__=false;window.__NINJA_ART_SOURCE__='approved-uploaded-assets';
Promise.all([0,1,2,3].map(i=>fetch(`${ATLAS_BASE}atlas-0${i}.txt?v=6`,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error(`Artwork chunk ${i} HTTP ${r.status}`);return r.text();}))).then(parts=>new Promise((resolve,reject)=>{atlas.onload=()=>{atlasReady=true;window.__NINJA_ART_READY__=true;resolve();};atlas.onerror=()=>reject(new Error('Artwork atlas decode failed'));atlas.src='data:image/webp;base64,'+parts.join('');})).catch(err=>{atlasError=true;console.error('[Ninja Climb] artwork load failed:',err);});
function show(id=''){panels.forEach(p=>$(p).classList.toggle('hidden',p!==id));}
function ww(){return Math.max(55,Math.min(75,W*.15));}
function sx(side){return side==='left'?ww()+P.w*.28:W-ww()-P.w*.28;}
function setSide(anim=true){const nx=sx(P.side);if(anim){P.fromX=P.x;P.toX=nx;P.t=0}else P.x=P.fromX=P.toX=nx;}
function resize(){const r=c.getBoundingClientRect();DPR=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,r.width*DPR);c.height=Math.max(1,r.height*DPR);W=r.width;H=r.height;ctx.setTransform(DPR,0,0,DPR,0,0);P.w=Math.max(48,W*.14);P.h=P.w*1.38;P.y=H*.69;setSide(false);}
addEventListener('resize',resize,{passive:true});resize();
function menu(){$('bestStart').textContent=best+' m';$('bankStart').textContent=bank;refreshShop();}
function sync(){$('altitude').textContent=Math.floor(alt);$('scrolls').textContent=runScrolls;}
function resetTimers(){next={enemy:.7,scroll:2,shield:12+Math.random()*5,shuriken:6.5,raven:9.5,dragon:22+Math.random()*8,roof:8,clothes:5};}
function start(){state='playing';paused=false;speed=118;alt=0;runScrolls=0;objects=[];particles=[];decor=[];shield=false;dragon=false;shieldT=dragonT=0;shake=0;revived=false;wallOff=bgOff=0;P.side='left';P.y=H*.69;P.inv=1;setSide(false);resetTimers();show();$('hud').classList.remove('hidden');$('pauseBtn').classList.remove('hidden');sync();}
function over(){if(state!=='playing')return;state='gameover';best=Math.max(best,Math.floor(alt));bank+=runScrolls;localStorage.ninjaBest=best;localStorage.ninjaScrolls=bank;$('finalAltitude').textContent=Math.floor(alt);$('hud').classList.add('hidden');$('pauseBtn').classList.add('hidden');$('reviveBtn').classList.toggle('hidden',revived||bank<500);show('gameOverPanel');menu();}
function jump(){if(state!=='playing'||paused||dragon)return;P.side=P.side==='left'?'right':'left';setSide(true);burst(P.x,P.y+P.h*.34,10,'#ead8bc');}
function togglePause(force){if(state!=='playing')return;paused=force??!paused;show(paused?'pausePanel':'');}
function spawn(type,side='center',y=-80,extra={}){objects.push({type,side,x:extra.x??0,y,vx:extra.vx||0,vy:extra.vy||0,phase:extra.phase||'move',timer:extra.timer||0,rot:Math.random()*6.2,dead:false,...extra});}
function enemy(){spawn(Math.random()<.72?'red':'black',Math.random()<.5?'left':'right',-90);}
function scroll(){spawn('scroll',Math.random()<.5?'left':'right',-70);}
function roof(){spawn('roof',Math.random()<.5?'left':'right',-90);}
function clothes(){decor.push({type:'clothes',y:-110});}
function shieldSpawn(){spawn('shield','center',-70,{x:W*(.34+Math.random()*.32)});}
function shuriken(){const l=Math.random()<.5;spawn('shuriken','center',H*(.24+Math.random()*.34),{x:l?ww():W-ww(),vx:(l?1:-1)*(155+alt*.012)});}
function raven(){spawn('raven','center',H*.13,{x:W*(.3+Math.random()*.4),phase:'hover',timer:1.05});}
function dragonSpawn(){spawn('dragon','center',-110,{x:W*.5,phase:'descend'});}
function burst(x,y,n,col){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*140,vy:(Math.random()-.75)*150,life:.35+Math.random()*.4,max:.75,size:2+Math.random()*4,col});}
function size(t){switch(t){case'red':case'black':return{w:W*.115,h:W*.16};case'raven':return{w:W*.14,h:W*.095};case'shuriken':return{w:W*.075,h:W*.075};case'scroll':return{w:W*.075,h:W*.075};case'shield':return{w:W*.095,h:W*.095};case'dragon':return{w:W*.19,h:W*.15};case'roof':return{w:W*.19,h:W*.105};default:return{w:50,h:50};}}
function rectP(){return{x:P.x-P.w*.24,y:P.y-P.h*.31,w:P.w*.48,h:P.h*.62};}
function rectO(o){const s=size(o.type);let k=.62;if(o.type==='roof')k=.56;if(o.type==='raven')k=.58;return{x:o.x-s.w*k/2,y:o.y-s.h*k/2,w:s.w*k,h:s.h*k};}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function update(dt){if(state!=='playing'||paused)return;if(P.inv>0)P.inv-=dt;const v=dragon?speed*3.05:speed;wallOff=(wallOff+v*dt)%520;bgOff=(bgOff+v*.018*dt)%H;alt+=v*dt/8.2;if(dragon)alt+=v*dt/9;speed=Math.min(195,118+alt*.019);if(!dragon&&P.t<1){P.t=Math.min(1,P.t+dt/P.dur);const q=1-Math.pow(1-P.t,3);P.x=P.fromX+(P.toX-P.fromX)*q;}if(shield&&(shieldT-=dt)<=0)shield=false;if(dragon){dragonT-=dt;P.y=Math.max(H*.39,P.y-dt*40);if(dragonT<=0){dragon=false;P.y=H*.69;P.inv=1;setSide(false);}}Object.keys(next).forEach(k=>next[k]-=dt);if(next.enemy<=0&&!dragon){enemy();next.enemy=Math.max(1.05,2.6-alt/1400)+Math.random()*.65;}if(next.scroll<=0){scroll();next.scroll=3+Math.random()*2.6;}if(next.shield<=0){shieldSpawn();next.shield=16+Math.random()*12;}if(next.shuriken<=0&&alt>65){shuriken();next.shuriken=Math.max(4.7,8.8-alt/700)+Math.random()*3;}if(next.raven<=0&&alt>115){raven();next.raven=Math.max(6.5,11-alt/700)+Math.random()*4;}if(next.dragon<=0&&alt>200){dragonSpawn();next.dragon=30+Math.random()*22;}if(next.roof<=0&&alt>120){roof();next.roof=8+Math.random()*8;}if(next.clothes<=0){clothes();next.clothes=11+Math.random()*10;}for(const d of decor)d.y+=v*dt;decor=decor.filter(d=>d.y<H+150);for(const o of objects){if(o.dead)continue;if(['red','black','scroll','shield','dragon','roof'].includes(o.type))o.y+=v*dt;if(['red','black','scroll','roof'].includes(o.type)){const s=size(o.type);o.x=o.side==='left'?ww()+s.w*.26:W-ww()-s.w*.26;}if(o.type==='shuriken'){o.x+=o.vx*dt;o.rot+=dt*9;}if(o.type==='raven'){if(o.phase==='hover'){o.timer-=dt;o.y=H*.14+Math.sin(performance.now()/105)*5;if(o.timer<=0){o.phase='dive';let dx=P.x-o.x,dy=P.y-o.y,L=Math.hypot(dx,dy)||1;o.vx=dx/L*310;o.vy=dy/L*310;}}else{o.x+=o.vx*dt;o.y+=o.vy*dt;}}if(o.type==='dragon'){if(o.phase==='descend'&&o.y>H*.21){o.phase='hover';o.timer=3.3;}else if(o.phase==='hover'){o.timer-=dt;o.y+=Math.sin(performance.now()/130)*.25;if(o.timer<=0)o.dead=true;}}if(o.y>H+170||o.x<-150||o.x>W+150)o.dead=true;if(!o.dead&&hit(rectP(),rectO(o))){if(o.type==='scroll'){runScrolls+=100;o.dead=true;burst(o.x,o.y,12,'#ffd24a');}else if(o.type==='shield'){shield=true;shieldT=5;o.dead=true;burst(o.x,o.y,15,'#54ddff');}else if(o.type==='dragon'){dragon=true;dragonT=7;shield=false;o.dead=true;objects.forEach(z=>{if(['red','black','raven','shuriken','roof'].includes(z.type))z.dead=true;});burst(P.x,P.y,24,'#ff9d18');shake=.35;}else if(['red','black','raven','shuriken','roof'].includes(o.type)){if(dragon){o.dead=true;burst(o.x,o.y,14,'#ff9d18');shake=.15;}else if(shield){shield=false;o.dead=true;burst(o.x,o.y,14,'#58e7ff');shake=.12;}else if(P.inv<=0){over();break;}}}}objects=objects.filter(o=>!o.dead);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-dt);sync();}
function clip(key){const r=A[key],sx=atlas.naturalWidth/600,sy=atlas.naturalHeight/987;return[r[0]*sx,r[1]*sy,r[2]*sx,r[3]*sy];}
function drawSprite(key,cx,cy,dw,dh,opt={}){if(!atlasReady)return false;const [sx,sy,sw,sh]=clip(key);const flip=!!opt.flip,rot=opt.rot||0,alpha=opt.alpha??1;ctx.save();ctx.globalAlpha*=alpha;ctx.translate(cx,cy);if(rot)ctx.rotate(rot);if(flip)ctx.scale(-1,1);ctx.drawImage(atlas,sx,sy,sw,sh,-dw/2,-dh/2,dw,dh);ctx.restore();return true;}
function drawCover(key,x,y,w,h,offY=0){if(!atlasReady)return false;const [sx,sy,sw,sh]=clip(key);const scale=Math.max(w/sw,h/sh);const cropW=w/scale,cropH=h/scale;const srcX=sx+(sw-cropW)/2;let srcY=sy+(sh-cropH)/2+(offY/Math.max(1,H))*Math.max(0,sh-cropH)*.4;srcY=Math.max(sy,Math.min(sy+sh-cropH,srcY));ctx.drawImage(atlas,srcX,srcY,cropW,cropH,x,y,w,h);return true;}
function fallbackBg(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#dc8065');g.addColorStop(.48,'#efc58a');g.addColorStop(1,'#8790ad');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}
function bg(){if(!drawCover('background',0,0,W,H,bgOff))fallbackBg();const haze=ctx.createLinearGradient(0,H*.2,0,H);haze.addColorStop(0,'rgba(255,225,194,.02)');haze.addColorStop(.62,'rgba(226,216,211,.05)');haze.addColorStop(1,'rgba(56,45,58,.13)');ctx.fillStyle=haze;ctx.fillRect(0,0,W,H);}
function wallTile(x,y,w,h,flip){if(drawSprite('wall',x+w/2,y+h/2,w,h,{flip}))return;ctx.fillStyle='#d59c65';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#8d5835';ctx.strokeRect(x,y,w,h);}
function walls(){const w=ww(),tileH=w*(354/95),off=wallOff%tileH;for(let y=-tileH+off;y<H+tileH;y+=tileH){wallTile(0,y,w,tileH,false);wallTile(W-w,y,w,tileH,true);}ctx.fillStyle='rgba(52,29,20,.32)';ctx.fillRect(w-4,0,4,H);ctx.fillRect(W-w,0,4,H);}
function drawClothes(y){const w=Math.min(W-2*ww()+8,W*.78),h=w*(83/250);if(drawSprite('clothes',W/2,y+h*.5,w,h))return;ctx.strokeStyle='#5d422f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(ww(),y);ctx.lineTo(W-ww(),y);ctx.stroke();}
function fallbackNinja(x,y,col,flip=false){ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.fillStyle='#151922';ctx.beginPath();ctx.arc(0,-15,12,0,Math.PI*2);ctx.fill();ctx.fillStyle=col;ctx.fillRect(-13,-25,26,7);ctx.fillRect(-10,-5,20,27);ctx.restore();}
function playerDraw(){if(dragon){const key=skin==='gold'?'dragonGold':'dragonBlue';const w=Math.min(W*.46,205),r=A[key],h=w*(r[3]/r[2]);if(!drawSprite(key,W*.5,P.y+Math.sin(performance.now()/90)*5,w,h))fallbackNinja(W*.5,P.y,skin==='gold'?'#e9b22e':'#1484ff');return;}const key=skin==='gold'?'playerGold':'playerBlue',r=A[key];const w=P.w*1.42,h=w*(r[3]/r[2]);if(!drawSprite(key,P.x,P.y-h*.04,w,h,{flip:P.side==='right'}))fallbackNinja(P.x,P.y,skin==='gold'?'#e9b22e':'#1484ff',P.side==='right');if(shield){const sw=Math.max(w*1.78,P.w*2),sh=sw*(97/103);if(!drawSprite('shield',P.x,P.y,sw,sh,{alpha:.82})){ctx.strokeStyle='#69e7ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(P.x,P.y,w*.82,0,Math.PI*2);ctx.stroke();}}}
function objectDraw(o){const s=size(o.type);if(o.type==='red'||o.type==='black'){const key=o.type==='red'?'enemyRed':'enemyBlack',r=A[key],w=s.w*1.56,h=w*(r[3]/r[2]);if(!drawSprite(key,o.x,o.y,w,h,{flip:o.side==='right'}))fallbackNinja(o.x,o.y,o.type==='red'?'#d3222d':'#202127',o.side==='right');}else if(o.type==='raven'){const w=s.w*1.35,h=w*(98/150);if(!drawSprite('raven',o.x,o.y,w,h,{flip:o.vx<0})){ctx.fillStyle='#171827';ctx.beginPath();ctx.ellipse(o.x,o.y,18,9,0,0,Math.PI*2);ctx.fill();}}else if(o.type==='shuriken'){const w=s.w*1.12;if(!drawSprite('shuriken',o.x,o.y,w,w*(86/87),{rot:o.rot})){ctx.fillStyle='#dce3e9';ctx.fillRect(o.x-w/2,o.y-w/2,w,w);}}else if(o.type==='scroll'){const w=s.w*1.18,h=w*(84/87);if(!drawSprite('scroll',o.x,o.y,w,h)){ctx.fillStyle='#e3c178';ctx.fillRect(o.x-w/2,o.y-h/2,w,h);}}else if(o.type==='shield'){const w=s.w*1.35,h=w*(97/103);if(!drawSprite('shield',o.x,o.y,w,h)){ctx.strokeStyle='#67e6ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(o.x,o.y,w*.45,0,Math.PI*2);ctx.stroke();}}else if(o.type==='dragon'){const w=s.w*1.55,h=w*(146/150);if(!drawSprite('dragon',o.x,o.y,w,h)){ctx.fillStyle='#df4b24';ctx.beginPath();ctx.ellipse(o.x,o.y,w*.45,h*.35,0,0,Math.PI*2);ctx.fill();}}else if(o.type==='roof'){const w=s.w*1.72,h=w*(112/174),flip=o.side==='right';const cx=o.side==='left'?ww()+w*.30:W-ww()-w*.30;if(!drawSprite('roof',cx,o.y,w,h,{flip})){ctx.fillStyle='#33384b';ctx.fillRect(cx-w/2,o.y-h/2,w,h);}}}
function render(){ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*9,(Math.random()-.5)*9);bg();for(const d of decor)drawClothes(d.y);walls();objects.forEach(objectDraw);playerDraw();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.col;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;if(dragon){ctx.fillStyle='rgba(255,162,40,.10)';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(255,239,173,.35)';ctx.lineWidth=2;for(let i=0;i<8;i++){let x=(i*61+performance.now()*.35)%W;ctx.beginPath();ctx.moveTo(x,H*.2);ctx.lineTo(x-45,H*.85);ctx.stroke();}}if(!atlasReady&&!atlasError&&state==='menu'){ctx.fillStyle='rgba(0,0,0,.18)';ctx.fillRect(0,H-34,W,34);ctx.fillStyle='rgba(255,255,255,.75)';ctx.font='700 10px system-ui';ctx.textAlign='center';ctx.fillText('LOADING HD ART…',W/2,H-14);}ctx.restore();}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop);}
function refreshShop(){const gb=$('goldSkinBtn');gb.textContent=goldUnlocked?(skin==='gold'?'SELECTED':'SELECT'):'UNLOCK';document.querySelector('[data-skin="gold"]').classList.toggle('active',skin==='gold');document.querySelector('[data-skin="blue"]').classList.toggle('active',skin==='blue');}
$('startBtn').onclick=start;$('retryBtn').onclick=start;$('pauseBtn').onclick=()=>togglePause();$('resumeBtn').onclick=()=>togglePause(false);$('restartBtn').onclick=start;$('shopBtn').onclick=()=>{show('shopPanel');refreshShop();};$('closeShopBtn').onclick=()=>show(state==='gameover'?'gameOverPanel':'startPanel');$('settingsBtn').onclick=()=>alert('Sound and vibration use your device settings.');
$('blueSkinBtn').onclick=()=>{skin='blue';localStorage.ninjaSkin=skin;refreshShop();};$('goldSkinBtn').onclick=()=>{if(!goldUnlocked){if(bank<4000){$('toast').textContent='Need 4,000 Scrolls';$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),1200);return;}bank-=4000;goldUnlocked=true;localStorage.ninjaGold='1';localStorage.ninjaScrolls=bank;}skin='gold';localStorage.ninjaSkin=skin;menu();};
$('reviveBtn').onclick=()=>{if(revived||bank<500)return;bank-=500;localStorage.ninjaScrolls=bank;revived=true;state='playing';objects=[];P.inv=2;shield=true;shieldT=2;show();$('hud').classList.remove('hidden');$('pauseBtn').classList.remove('hidden');};
c.addEventListener('pointerdown',e=>{e.preventDefault();if(state==='playing'&&!paused)jump();},{passive:false});document.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowLeft'||e.code==='ArrowRight'){e.preventDefault();jump();}});
menu();requestAnimationFrame(loop);if(auto)setTimeout(start,250);
})();
