(() => {
  'use strict';
  const VERSION='58';
  const SPRITE_URL='audio/sfx-sprite.mp3?v=58';
  const CUES={reload:{start:0,dur:1.50,gain:.86},shot:{start:1.662,dur:1.55,gain:.95},impact:{start:3.379,dur:1.04,gain:.78},snort:{start:4.585,dur:2.0,gain:.40},grunt:{start:6.775,dur:2.0,gain:.46}};
  const ACtor=window.AudioContext||window.webkitAudioContext;
  let ctx=null,master=null,sfxBus=null,ambienceBus=null,sprite=null,unlocked=false,ambienceStarted=false,deerTimer=0,birdTimer=0,lastImpact=0,lastNotify='',spriteBytes=null;
  const spriteFetch=fetch(SPRITE_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`SFX ${r.status}`);return r.arrayBuffer()}).then(b=>{spriteBytes=b;return b}).catch(e=>{console.error('[audio58] SFX fetch failed',e);throw e});
  function setupGraph(){if(ctx||!ACtor)return;ctx=new ACtor({latencyHint:'interactive'});master=ctx.createDynamicsCompressor();master.threshold.value=-12;master.knee.value=14;master.ratio.value=4;master.attack.value=.003;master.release.value=.22;const out=ctx.createGain();out.gain.value=.92;sfxBus=ctx.createGain();sfxBus.gain.value=1;ambienceBus=ctx.createGain();ambienceBus.gain.value=.72;sfxBus.connect(master);ambienceBus.connect(master);master.connect(out);out.connect(ctx.destination)}
  async function ensureAudio(){setupGraph();if(!ctx)return false;try{if(ctx.state!=='running')await ctx.resume()}catch(e){console.warn('[audio58] resume failed',e)}unlocked=ctx.state==='running';if(!sprite){try{const bytes=spriteBytes||await spriteFetch;sprite=await ctx.decodeAudioData(bytes.slice(0))}catch(e){console.error('[audio58] decode failed',e)}}if(unlocked&&!ambienceStarted)startAmbience();return unlocked}
  function playCue(name,volume=1,delay=0,rate=1){if(!ctx||ctx.state!=='running'||!sprite)return false;const c=CUES[name];if(!c)return false;const src=ctx.createBufferSource(),g=ctx.createGain();src.buffer=sprite;src.playbackRate.value=rate;g.gain.value=Math.min(1.2,c.gain*volume);src.connect(g).connect(sfxBus);try{src.start(ctx.currentTime+delay,c.start,c.dur)}catch(e){console.warn('[audio58] cue',name,e);return false}return true}
  function uiClick(){if(!ctx||ctx.state!=='running')return;const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(780,t);o.frequency.exponentialRampToValueAtTime(1180,t+.055);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.055,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+.08);o.connect(g).connect(sfxBus);o.start(t);o.stop(t+.085)}
  function uiNotify(){if(!ctx||ctx.state!=='running')return;const t=ctx.currentTime;[[660,0],[990,.085]].forEach(([f,d])=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,t+d);g.gain.exponentialRampToValueAtTime(.075,t+d+.012);g.gain.exponentialRampToValueAtTime(.0001,t+d+.18);o.connect(g).connect(sfxBus);o.start(t+d);o.stop(t+d+.19)})}
  function startAmbience(){if(!ctx||ctx.state!=='running'||ambienceStarted)return;ambienceStarted=true;const sr=Math.min(24000,ctx.sampleRate),seconds=4,n=Math.floor(sr*seconds),buf=ctx.createBuffer(1,n,sr),a=buf.getChannelData(0);let seed=219731,lp=0;for(let i=0;i<n;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const w=seed/4294967296*2-1;lp+=.012*(w-lp);const t=i/sr;a[i]=lp*(.50+.18*Math.sin(t*.61)+.08*Math.sin(t*1.17+1.2))*.30}const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=buf;src.loop=true;filter.type='lowpass';filter.frequency.value=1150;filter.Q.value=.35;g.gain.value=.18;src.connect(filter).connect(g).connect(ambienceBus);src.start();scheduleBird();scheduleDeer()}
  function scheduleBird(){clearTimeout(birdTimer);if(!ambienceStarted)return;birdTimer=setTimeout(()=>{if(ctx?.state==='running'&&document.visibilityState==='visible'){const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(1700+Math.random()*900,t);o.frequency.exponentialRampToValueAtTime(2600+Math.random()*900,t+.07);o.frequency.exponentialRampToValueAtTime(1500+Math.random()*600,t+.18);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.018,t+.018);g.gain.exponentialRampToValueAtTime(.0001,t+.2);o.connect(g).connect(ambienceBus);o.start(t);o.stop(t+.21)}scheduleBird()},1800+Math.random()*4600)}
  function scheduleDeer(){clearTimeout(deerTimer);if(!ambienceStarted)return;deerTimer=setTimeout(()=>{if(ctx?.state==='running'&&document.visibilityState==='visible'&&!document.querySelector('#shop')?.classList.contains('open'))playCue(Math.random()<.58?'snort':'grunt',.62,0,.96+Math.random()*.08);scheduleDeer()},6500+Math.random()*7000)}
  function duckAmbience(ms=900){if(!ctx||!ambienceBus)return;const t=ctx.currentTime;ambienceBus.gain.cancelScheduledValues(t);ambienceBus.gain.setValueAtTime(ambienceBus.gain.value,t);ambienceBus.gain.linearRampToValueAtTime(.25,t+.03);ambienceBus.gain.setTargetAtTime(.72,t+ms/1000,.35)}
  document.addEventListener('pointerdown',e=>{const id=e.target?.id;ensureAudio().then(ok=>{if(!ok)return;if(id==='start'){uiClick();return}if(id==='fire'){duckAmbience(1050);playCue('shot',1);return}if(id==='reload'){duckAmbience(1500);playCue('reload',1);return}if(e.target?.closest?.('button,.rifle'))uiClick()})},true);
  const dmg=document.querySelector('#dmg');if(dmg)new MutationObserver(()=>{if(!dmg.classList.contains('show')||!dmg.textContent.trim())return;const now=performance.now();if(now-lastImpact<160)return;lastImpact=now;ensureAudio().then(()=>{duckAmbience(650);playCue('impact',1,0);playCue('grunt',.72,.08,.98+Math.random()*.04)})}).observe(dmg,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class']});
  const msg=document.querySelector('#msg');if(msg)new MutationObserver(()=>{const text=msg.textContent.trim();if(!msg.classList.contains('show')||!text||text===lastNotify)return;lastNotify=text;if(/BAG FULL|DEER SOLD|PURCHASE|EQUIPPED|SHOT BLOCKED|DEER DOWN|READY|RELOAD/i.test(text))ensureAudio().then(uiNotify);setTimeout(()=>{if(lastNotify===text)lastNotify=''},1100)}).observe(msg,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class']});
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&unlocked)ensureAudio()});
  window.__forestAudio58={version:VERSION,ensureAudio,playCue,status:()=>({unlocked,context:ctx?.state||'none',spriteReady:!!sprite,ambienceStarted})};
  console.info('[Forest Stalker] audio58 installed');
})();