(() => {
  'use strict';
  const VERSION='59';
  const SPRITE='audio/sfx-sprite.mp3?v=59';
  const CUES={reload:{start:0,dur:1.50,vol:0.95},shot:{start:1.662,dur:1.55,vol:1.0},impact:{start:3.379,dur:1.04,vol:0.88},snort:{start:4.585,dur:2.0,vol:0.52},grunt:{start:6.775,dur:2.0,vol:0.58}};
  const voices={};
  for(const name of Object.keys(CUES)){const a=new Audio(SPRITE);a.preload='auto';a.playsInline=true;a.crossOrigin='anonymous';voices[name]=a;}
  let unlocked=false,audioCtx=null,natureGain=null,natureStarted=false,lastImpact=0,lastMsg='',deerTimer=0,birdTimer=0;
  function playSegment(name,volume=1,rate=1){const a=voices[name],c=CUES[name];if(!a||!c)return false;try{a.pause();a.playbackRate=rate;a.volume=Math.min(1,c.vol*volume);a.currentTime=c.start;const p=a.play();if(p?.catch)p.catch(e=>console.warn(`[audio59] ${name} play blocked`,e));clearTimeout(a.__stopTimer);a.__stopTimer=setTimeout(()=>{try{a.pause();a.currentTime=c.start}catch{}},Math.max(80,c.dur*1000/rate));return true}catch(e){console.warn('[audio59] segment failed',name,e);return false}}
  function ensureCtx(){if(!audioCtx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;audioCtx=new AC({latencyHint:'interactive'});}if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});return audioCtx}
  function startNature(){const ctx=ensureCtx();if(!ctx||natureStarted)return;natureStarted=true;natureGain=ctx.createGain();natureGain.gain.value=.17;natureGain.connect(ctx.destination);const sr=Math.min(24000,ctx.sampleRate),secs=4,count=Math.floor(sr*secs),buf=ctx.createBuffer(1,count,sr),data=buf.getChannelData(0);let seed=681231,lp=0;for(let i=0;i<count;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const white=(seed/4294967296)*2-1;lp+=.012*(white-lp);const t=i/sr;data[i]=lp*(.34+.08*Math.sin(t*.47)+.05*Math.sin(t*.89+1.1));}const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter();src.buffer=buf;src.loop=true;filter.type='lowpass';filter.frequency.value=950;filter.Q.value=.25;src.connect(filter).connect(natureGain);src.start();scheduleBird();scheduleDeer()}
  function tone(freq=820,dur=.075,gain=.04,type='sine'){const ctx=ensureCtx();if(!ctx||ctx.state!=='running')return;const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*1.12,t+dur*.55);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+dur+.01)}
  function uiClick(){tone(720,.065,.026,'sine')} function notify(){tone(620,.11,.04);setTimeout(()=>tone(930,.14,.038),75)}
  function scheduleBird(){clearTimeout(birdTimer);birdTimer=setTimeout(()=>{if(natureStarted&&document.visibilityState==='visible'){const ctx=ensureCtx();if(ctx?.state==='running'){const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(1850+Math.random()*650,t);o.frequency.exponentialRampToValueAtTime(3000+Math.random()*500,t+.08);o.frequency.exponentialRampToValueAtTime(1600+Math.random()*450,t+.19);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.016,t+.018);g.gain.exponentialRampToValueAtTime(.0001,t+.21);o.connect(g).connect(natureGain||ctx.destination);o.start(t);o.stop(t+.22);}}scheduleBird();},1900+Math.random()*4300)}
  function scheduleDeer(){clearTimeout(deerTimer);deerTimer=setTimeout(()=>{if(unlocked&&document.visibilityState==='visible'&&!document.querySelector('#shop')?.classList.contains('open'))playSegment(Math.random()<.6?'snort':'grunt',.58,.97+Math.random()*.06);scheduleDeer();},6500+Math.random()*6500)}
  function unlockAutomaticVoices(){for(const name of ['impact','snort','grunt']){const a=voices[name],c=CUES[name];try{a.volume=.001;a.currentTime=c.start;const p=a.play();if(p?.then)p.then(()=>setTimeout(()=>{try{a.pause();a.currentTime=c.start;a.volume=c.vol}catch{}},35)).catch(()=>{});}catch{}}unlocked=true}
  document.addEventListener('pointerdown',e=>{const id=e.target?.id;ensureCtx();if(id==='start'){unlockAutomaticVoices();startNature();uiClick();return}if(id==='fire'){const ammo=parseInt(document.querySelector('#ammo')?.textContent||'0',10),shop=document.querySelector('#shop')?.classList.contains('open'),intro=getComputedStyle(document.querySelector('#intro')).display!=='none';if(ammo>0&&!shop&&!intro)playSegment('shot',1,1);return}if(id==='reload'){const ammo=parseInt(document.querySelector('#ammo')?.textContent||'5',10),shop=document.querySelector('#shop')?.classList.contains('open'),intro=getComputedStyle(document.querySelector('#intro')).display!=='none';if(ammo<5&&!shop&&!intro)playSegment('reload',1,1);return}if(e.target?.closest?.('button,.rifle'))uiClick();},true);
  const dmg=document.querySelector('#dmg');if(dmg)new MutationObserver(()=>{if(!dmg.classList.contains('show')||!dmg.textContent.trim())return;const now=performance.now();if(now-lastImpact<180)return;lastImpact=now;playSegment('impact',.95,1);setTimeout(()=>playSegment('grunt',.62,.99),90)}).observe(dmg,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class']});
  const msg=document.querySelector('#msg');if(msg)new MutationObserver(()=>{const text=msg.textContent.trim();if(!msg.classList.contains('show')||!text||text===lastMsg)return;lastMsg=text;if(/BAG FULL|DEER SOLD|NOT ENOUGH|EQUIPPED|SHOT BLOCKED|DEER DOWN|READY|RELOAD/i.test(text))notify();setTimeout(()=>{if(lastMsg===text)lastMsg=''},1000)}).observe(msg,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class']});
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&unlocked){ensureCtx();startNature()}});
  window.__forestAudio59={version:VERSION,playSegment,status:()=>({unlocked,natureStarted,context:audioCtx?.state||'none'})};
  console.info('[Forest Stalker] audio59 HTMLAudio hotfix installed');
})();