import * as THREE from 'three';
const $=s=>document.querySelector(s);
const canvas=$('#g'),R=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});R.setPixelRatio(Math.min(devicePixelRatio,1.55));R.setSize(innerWidth,innerHeight,false);R.shadowMap.enabled=true;R.shadowMap.type=THREE.PCFSoftShadowMap;R.toneMapping=THREE.ACESFilmicToneMapping;R.toneMappingExposure=1.03;
const S=new THREE.Scene();S.background=new THREE.Color(0x8fa08e);S.fog=new THREE.FogExp2(0x718071,.0145);const C=new THREE.PerspectiveCamera(18,innerWidth/innerHeight,.08,240);C.position.set(0,1.72,0);C.rotation.order='YXZ';S.add(C);S.add(new THREE.HemisphereLight(0xdce7d8,0x253022,1.35));const sun=new THREE.DirectionalLight(0xffe7bd,2.1);sun.position.set(-30,45,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);S.add(sun);
const ty=(x,z)=>Math.sin(x*.09)*.24+Math.cos(z*.075)*.22+Math.sin((x+z)*.035)*.18;
const gg=new THREE.PlaneGeometry(180,180,70,70);gg.rotateX(-Math.PI/2);for(let i=0;i<gg.attributes.position.count;i++){const x=gg.attributes.position.getX(i),z=gg.attributes.position.getZ(i);gg.attributes.position.setY(i,ty(x,z))}gg.computeVertexNormals();const ground=new THREE.Mesh(gg,new THREE.MeshStandardMaterial({color:0x354a30,roughness:1}));ground.receiveShadow=true;S.add(ground);
let seed=98731;const rnd=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296),dum=new THREE.Object3D();const trunkG=new THREE.CylinderGeometry(.14,.28,3.8,7),trunkM=new THREE.MeshStandardMaterial({color:0x4b3927}),crownG=new THREE.ConeGeometry(1.25,4.3,8),crownM=new THREE.MeshStandardMaterial({color:0x29452d}),trees=new THREE.InstancedMesh(trunkG,trunkM,210),crowns=new THREE.InstancedMesh(crownG,crownM,210);trees.castShadow=crowns.castShadow=true;for(let i=0;i<210;i++){const a=rnd()*Math.PI*2,r=10+rnd()*72,x=Math.cos(a)*r,z=Math.sin(a)*r,s=.62+rnd()*1.22,y=ty(x,z);dum.position.set(x,y+1.9*s,z);dum.scale.setScalar(s);dum.rotation.y=rnd()*6.28;dum.updateMatrix();trees.setMatrixAt(i,dum.matrix);dum.position.set(x,y+4.05*s,z);dum.scale.setScalar(s*(.88+rnd()*.22));dum.updateMatrix();crowns.setMatrixAt(i,dum.matrix)}S.add(trees,crowns);
const shrubG=new THREE.IcosahedronGeometry(.45,1),shrubM=new THREE.MeshStandardMaterial({color:0x45613c}),shrubs=new THREE.InstancedMesh(shrubG,shrubM,120);for(let i=0;i<120;i++){const a=rnd()*Math.PI*2,r=8+rnd()*70,x=Math.cos(a)*r,z=Math.sin(a)*r,s=.4+rnd()*.9;dum.position.set(x,ty(x,z)+.18,z);dum.scale.set(s*1.4,s*.65,s);dum.rotation.y=rnd()*6.28;dum.updateMatrix();shrubs.setMatrixAt(i,dum.matrix)}S.add(shrubs);
const SNIPERS=[{id:0,name:'RANGER .308',price:0,damage:42,mag:5,delay:.72,sway:1,zoom:18,desc:'Balanced starter rifle'},{id:1,name:'HUNTER X',price:600,damage:55,mag:5,delay:.62,sway:.86,zoom:17,desc:'Higher damage'},{id:2,name:'VANGUARD',price:1400,damage:48,mag:7,delay:.48,sway:.82,zoom:19,desc:'Fast follow-up shots'},{id:3,name:'SILVER FOX',price:2600,damage:68,mag:5,delay:.78,sway:.56,zoom:16,desc:'Very stable & powerful'},{id:4,name:'TITAN .50',price:5200,damage:100,mag:3,delay:1.05,sway:.72,zoom:15,desc:'One-shot body potential'}];
let save;try{save=JSON.parse(localStorage.getItem('forestStalkerV5'))||{coins:0,owned:[0],equipped:0}}catch{save={coins:0,owned:[0],equipped:0}};const persist=()=>localStorage.setItem('forestStalkerV5',JSON.stringify(save));
function makeDeer(i){const root=new THREE.Group(),fur=new THREE.MeshStandardMaterial({color:i%2?0x7a4a2a:0x865433,roughness:.95}),dark=new THREE.MeshStandardMaterial({color:0x34251c,roughness:1}),cream=new THREE.MeshStandardMaterial({color:0xc6ae88,roughness:1}),ant=new THREE.MeshStandardMaterial({color:0x4a3826,roughness:1});const add=(g,m,p,s=[1,1,1],r=[0,0,0])=>{const q=new THREE.Mesh(g,m);q.position.set(...p);q.scale.set(...s);q.rotation.set(...r);q.castShadow=true;root.add(q);return q};add(new THREE.SphereGeometry(1,18,14),fur,[0,1.15,0],[1.28,.62,.54]);add(new THREE.SphereGeometry(.44,16,12),fur,[1.36,2.14,0],[1,.72,.7]);add(new THREE.CylinderGeometry(.20,.34,1.2,10),fur,[1.02,1.65,0],[1,1,1],[0,0,-.48]);add(new THREE.SphereGeometry(.18,12,9),dark,[1.76,2.08,0],[1.2,.6,.65]);add(new THREE.ConeGeometry(.14,.42,9),fur,[1.3,2.5,.25],[1,.9,.65],[0,0,-.3]);add(new THREE.ConeGeometry(.14,.42,9),fur,[1.3,2.5,-.25],[1,.9,.65],[0,0,-.3]);const legs=[];for(const [x,z] of [[.64,.29],[.64,-.29],[-.64,.29],[-.64,-.29]]){const upper=add(new THREE.CylinderGeometry(.07,.11,.78,8),fur,[x,.62,z]);const lower=add(new THREE.CylinderGeometry(.045,.065,.72,8),dark,[x,.0,z]);legs.push({upper,lower,phase:z>0?0:Math.PI})}add(new THREE.ConeGeometry(.18,.55,9),cream,[-1.25,1.33,0],[1,.8,.7],[0,0,1.18]);for(const s of [-1,1]){add(new THREE.CylinderGeometry(.03,.045,.67,7),ant,[1.3,2.7,.12*s],[.08*s,0,-.25]);add(new THREE.CylinderGeometry(.025,.035,.43,7),ant,[1.18,2.98,.2*s],[.5*s,0,-.35])}
 const invisible=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false});const body=new THREE.Mesh(new THREE.SphereGeometry(1.02,10,8),invisible),head=new THREE.Mesh(new THREE.SphereGeometry(.44,10,8),invisible);body.position.set(0,1.15,0);head.position.set(1.36,2.14,0);body.userData={deer:null,zone:'body'};head.userData={deer:null,zone:'head'};root.add(body,head);const d={root,legs,body,head,hp:100,state:'wander',t:rnd()*10,speed:.7+rnd()*.45,dir:rnd()*6.28,respawn:0};body.userData.deer=head.userData.deer=d;root.userData.deer=d;S.add(root);spawnDeer(d,true);return d}
const DEER=[];for(let i=0;i<5;i++)DEER.push(makeDeer(i));
function spawnDeer(d,initial=false){const a=rnd()*Math.PI*2,r=initial?25+rnd()*35:30+rnd()*35;d.root.position.set(Math.cos(a)*r,0,Math.sin(a)*r);d.root.position.y=ty(d.root.position.x,d.root.position.z);d.hp=100;d.state='wander';d.t=rnd()*5;d.dir=a+Math.PI+(rnd()-.5)*1.8;d.root.rotation.set(0,-d.dir+Math.PI/2,0);d.root.visible=true}
function animateDeer(d,dt){if(!d.root.visible){d.respawn-=dt;if(d.respawn<=0)spawnDeer(d);return}d.t+=dt;let speed=d.speed;if(d.state==='flee')speed=5.2;else if(d.state==='hit')speed=3.8;else if(d.state==='dead'){d.root.rotation.z=THREE.MathUtils.lerp(d.root.rotation.z,Math.PI/2,1-Math.exp(-4*dt));d.respawn-=dt;if(d.respawn<=0){d.root.visible=false;d.respawn=1.4}return}
 if(d.state==='wander'&&rnd()<.006)d.dir+=(rnd()-.5)*1.4;if((d.state==='flee'||d.state==='hit')&&d.t>4.2){d.state='wander';d.t=0}
 d.root.position.x+=Math.cos(d.dir)*speed*dt;d.root.position.z+=Math.sin(d.dir)*speed*dt;const rr=Math.hypot(d.root.position.x,d.root.position.z);if(rr>72||rr<14){d.dir=Math.atan2(-d.root.position.z,-d.root.position.x)+(rnd()-.5)*.8}d.root.position.y=ty(d.root.position.x,d.root.position.z);d.root.rotation.y=-d.dir+Math.PI/2;
 const f=d.state==='wander'?4.2:10.5,A=d.state==='wander'?.16:.62,p=d.t*f;d.legs.forEach((L,i)=>{const w=Math.sin(p+L.phase+(i>1?Math.PI:0))*A;L.upper.rotation.z=w;L.lower.rotation.z=-Math.max(0,w)*.65});d.root.position.y+=Math.abs(Math.sin(p))*(d.state==='wander'?.012:.06)}
let run=false,shots=5,reserve=20,bolting=false,reloading=false,totalShots=0,hits=0,kills=0,carcasses=0,yaw=0,pitch=0,tyaw=0,tpitch=0,recoil=0,last=performance.now();const ray=new THREE.Raycaster();
const ui=()=>{const gun=SNIPERS[save.equipped];$('#ammo').textContent=shots;$('#reserve').textContent=reserve;$('#score').textContent=kills;$('#coins').textContent=save.coins;$('#bag').textContent=carcasses;$('#gunName').textContent=gun.name;$('#acc').textContent=(totalShots?Math.round(hits/totalShots*100):100)+'%';};
function note(t,ms=700){const m=$('#msg');m.textContent=t;m.classList.add('show');clearTimeout(note.t);note.t=setTimeout(()=>m.classList.remove('show'),ms)}function pop(t,good=true){const e=$('#dmg');e.textContent=t;e.className='dmg show '+(good?'good':'');setTimeout(()=>e.classList.remove('show'),600)}
function shoot(){if(!run||bolting||reloading)return;const gun=SNIPERS[save.equipped];if(shots<=0){note('RELOAD');return}shots--;totalShots++;bolting=true;recoil=.055;ui();setTimeout(()=>bolting=false,gun.delay*1000);ray.setFromCamera(new THREE.Vector2(0,0),C);const targets=[];DEER.forEach(d=>{if(d.root.visible&&d.state!=='dead')targets.push(d.head,d.body)});const h=ray.intersectObjects(targets,false)[0];if(!h){note('MISS',420);return}hits++;const d=h.object.userData.deer,headshot=h.object.userData.zone==='head',damage=headshot?100:gun.damage;d.hp=Math.max(0,d.hp-damage);pop(headshot?'HEADSHOT · -100':'-'+damage+' DMG');if(d.hp<=0){d.state='dead';d.t=0;d.respawn=1.1;kills++;carcasses++;note('DEER DOWN · +1 HUNT',900)}else{d.state='hit';d.t=0;d.dir=Math.atan2(d.root.position.z,d.root.position.x)+(rnd()-.5)*.45;note('HIT · '+d.hp+' HP',650)}ui()}
function reload(){if(!run||reloading||bolting)return;const gun=SNIPERS[save.equipped];if(shots>=gun.mag||reserve<=0)return;reloading=true;note('RELOADING…',1000);setTimeout(()=>{const n=Math.min(gun.mag-shots,reserve);shots+=n;reserve-=n;reloading=false;ui()},1050)}
function openShop(){run=false;renderShop();$('#shop').classList.add('open')}function closeShop(){run=true;$('#shop').classList.remove('open')}
function renderShop(){const list=$('#rifles');list.innerHTML='';SNIPERS.forEach(g=>{const owned=save.owned.includes(g.id),equipped=save.equipped===g.id,card=document.createElement('button');card.className='rifle '+(equipped?'equipped':'');card.innerHTML=`<div><strong>${g.name}</strong><small>${g.desc}</small><em>DMG ${g.damage} · MAG ${g.mag} · ${g.delay.toFixed(2)}s</em></div><span>${equipped?'EQUIPPED':owned?'EQUIP':g.price+' 🪙'}</span>`;card.onclick=()=>{if(equipped)return;if(owned){save.equipped=g.id;shots=g.mag;reserve=20;persist();renderShop();ui();return}if(save.coins>=g.price){save.coins-=g.price;save.owned.push(g.id);save.equipped=g.id;shots=g.mag;reserve=20;persist();renderShop();ui()}else note('NOT ENOUGH COINS')};list.appendChild(card)});$('#sellCount').textContent=carcasses;$('#sellValue').textContent=carcasses*90}
$('#sell').onclick=()=>{if(!carcasses)return;save.coins+=carcasses*90;carcasses=0;persist();renderShop();ui()};$('#shopBtn').onclick=openShop;$('#closeShop').onclick=closeShop;$('#fire').onpointerdown=e=>{e.preventDefault();shoot()};$('#reload').onpointerdown=e=>{e.preventDefault();reload()};$('#start').onclick=()=>{$('#intro').style.display='none';run=true;ui()};
let drag=false,lx=0,ly=0;addEventListener('pointerdown',e=>{if(!run||e.target.closest?.('button'))return;drag=true;lx=e.clientX;ly=e.clientY});addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;tyaw-=dx*.0018;tpitch=Math.max(-.62,Math.min(.62,tpitch-dy*.0016))});addEventListener('pointerup',()=>drag=false);addEventListener('pointercancel',()=>drag=false);
function loop(now){requestAnimationFrame(loop);const dt=Math.min(.033,(now-last)/1000);last=now;DEER.forEach(d=>animateDeer(d,dt));const gun=SNIPERS[save.equipped],sway=(run?gun.sway:0),t=now*.001;yaw=THREE.MathUtils.lerp(yaw,tyaw,1-Math.exp(-16*dt));pitch=THREE.MathUtils.lerp(pitch,tpitch,1-Math.exp(-16*dt));recoil=THREE.MathUtils.lerp(recoil,0,1-Math.exp(-15*dt));C.rotation.y=yaw+Math.sin(t*1.2)*.0011*sway;C.rotation.x=pitch+Math.sin(t*.92)*.0008*sway+recoil;C.fov=gun.zoom;C.updateProjectionMatrix();let nearest=999;DEER.forEach(d=>{if(d.root.visible)nearest=Math.min(nearest,C.position.distanceTo(d.root.position))});$('#range').textContent=Math.round(nearest)+' m';R.render(S,C)}requestAnimationFrame(loop);addEventListener('resize',()=>{R.setSize(innerWidth,innerHeight,false);C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix()});ui();