import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { clone as cloneSkeleton } from 'three/addons/utils/SkeletonUtils.js';

const $=s=>document.querySelector(s);
const canvas=$('#g');
const R=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
R.setPixelRatio(Math.min(devicePixelRatio,1.55));R.setSize(innerWidth,innerHeight,false);R.shadowMap.enabled=true;R.shadowMap.type=THREE.PCFSoftShadowMap;R.toneMapping=THREE.ACESFilmicToneMapping;R.toneMappingExposure=1.04;R.outputColorSpace=THREE.SRGBColorSpace;
const S=new THREE.Scene();S.background=new THREE.Color(0x8c9e8c);S.fog=new THREE.FogExp2(0x718071,.0148);
const C=new THREE.PerspectiveCamera(17.5,innerWidth/innerHeight,.08,240);C.position.set(0,1.72,0);C.rotation.order='YXZ';S.add(C);
S.add(new THREE.HemisphereLight(0xdce7d9,0x253024,1.36));
const sun=new THREE.DirectionalLight(0xffe7bd,2.15);sun.position.set(-30,45,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);S.add(sun);
const ty=(x,z)=>Math.sin(x*.09)*.24+Math.cos(z*.075)*.22+Math.sin((x+z)*.035)*.18;
const gg=new THREE.PlaneGeometry(180,180,70,70);gg.rotateX(-Math.PI/2);for(let i=0;i<gg.attributes.position.count;i++){const x=gg.attributes.position.getX(i),z=gg.attributes.position.getZ(i);gg.attributes.position.setY(i,ty(x,z))}gg.computeVertexNormals();const ground=new THREE.Mesh(gg,new THREE.MeshStandardMaterial({color:0x354a30,roughness:1}));ground.receiveShadow=true;S.add(ground);
let seed=98731;const rnd=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296),dum=new THREE.Object3D();
const trunkG=new THREE.CylinderGeometry(.14,.28,3.8,7),trunkM=new THREE.MeshStandardMaterial({color:0x4b3927}),crownG=new THREE.ConeGeometry(1.25,4.3,8),crownM=new THREE.MeshStandardMaterial({color:0x29452d}),trees=new THREE.InstancedMesh(trunkG,trunkM,210),crowns=new THREE.InstancedMesh(crownG,crownM,210);trees.castShadow=crowns.castShadow=true;
for(let i=0;i<210;i++){const a=rnd()*Math.PI*2,r=11+rnd()*72,x=Math.cos(a)*r,z=Math.sin(a)*r,s=.62+rnd()*1.22,y=ty(x,z);dum.position.set(x,y+1.9*s,z);dum.scale.setScalar(s);dum.rotation.y=rnd()*6.28;dum.updateMatrix();trees.setMatrixAt(i,dum.matrix);dum.position.set(x,y+4.05*s,z);dum.scale.setScalar(s*(.88+rnd()*.22));dum.updateMatrix();crowns.setMatrixAt(i,dum.matrix)}S.add(trees,crowns);
const shrubG=new THREE.IcosahedronGeometry(.45,1),shrubM=new THREE.MeshStandardMaterial({color:0x45613c}),shrubs=new THREE.InstancedMesh(shrubG,shrubM,120);for(let i=0;i<120;i++){const a=rnd()*Math.PI*2,r=9+rnd()*70,x=Math.cos(a)*r,z=Math.sin(a)*r,s=.4+rnd()*.9;dum.position.set(x,ty(x,z)+.18,z);dum.scale.set(s*1.4,s*.65,s);dum.rotation.y=rnd()*6.28;dum.updateMatrix();shrubs.setMatrixAt(i,dum.matrix)}S.add(shrubs);

const SNIPERS=[
{id:0,name:'RANGER .308',price:0,damage:42,mag:5,fireDelay:.34,reload:1.45,sway:1,scope:6,desc:'Balanced starter rifle'},
{id:1,name:'HUNTER X',price:600,damage:55,mag:5,fireDelay:.30,reload:1.35,sway:.86,scope:6,desc:'Higher stopping power'},
{id:2,name:'VANGUARD',price:1400,damage:50,mag:5,fireDelay:.23,reload:1.15,sway:.78,scope:7,desc:'Fast follow-up shots'},
{id:3,name:'SILVER FOX',price:2600,damage:70,mag:5,fireDelay:.38,reload:1.30,sway:.52,scope:8,desc:'Very stable and powerful'},
{id:4,name:'TITAN .50',price:5200,damage:100,mag:5,fireDelay:.52,reload:1.65,sway:.66,scope:10,desc:'One-shot body potential'}];
let save;try{save=JSON.parse(localStorage.getItem('forestStalkerV5'))||{}}catch{save={}};
save={coins:Number(save.coins)||0,owned:Array.isArray(save.owned)?save.owned:[0],equipped:Number.isInteger(save.equipped)?save.equipped:0,kills:Number(save.kills)||0,bag:Math.min(5,Number(save.bag)||0)};if(!save.owned.includes(0))save.owned.unshift(0);if(!SNIPERS[save.equipped]||!save.owned.includes(save.equipped))save.equipped=0;
const persist=()=>{try{localStorage.setItem('forestStalkerV5',JSON.stringify(save))}catch{}};

const AUDIO_URL='audio/sfx-sprite.mp3?v=54';
const CUES={reload:{start:0,dur:1.50,gain:.83},shot:{start:1.662,dur:1.55,gain:.96},impact:{start:3.379,dur:1.04,gain:.78},snort:{start:4.585,dur:2.0,gain:.43},grunt:{start:6.775,dur:2.0,gain:.50}};
let audioBytes=null,AC=null,audioBuffer=null,master=null,natureStarted=false,nextDeerCall=performance.now()+5000;
const audioPreload=fetch(AUDIO_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('audio '+r.status);return r.arrayBuffer()}).then(b=>audioBytes=b);
async function initAudio(){if(!AC){AC=new(window.AudioContext||window.webkitAudioContext)();master=AC.createDynamicsCompressor();master.threshold.value=-14;master.knee.value=12;master.ratio.value=5;master.attack.value=.003;master.release.value=.20;master.connect(AC.destination)}await AC.resume();if(!audioBytes)await audioPreload;if(!audioBuffer)audioBuffer=await AC.decodeAudioData(audioBytes.slice(0));if(!natureStarted)startNature();}
function playCue(name,{volume=1,rate=1,pan=0,delay=0}={}){if(!AC||!audioBuffer||!master)return;const c=CUES[name];if(!c)return;const src=AC.createBufferSource(),g=AC.createGain();src.buffer=audioBuffer;src.playbackRate.value=rate;g.gain.value=Math.min(1.25,c.gain*volume);if(AC.createStereoPanner){const p=AC.createStereoPanner();p.pan.value=Math.max(-1,Math.min(1,pan));src.connect(p).connect(g)}else src.connect(g);g.connect(master);src.start(AC.currentTime+delay,c.start,c.dur)}
function startNature(){natureStarted=true;const n=AC.createBufferSource(),g=AC.createGain(),f=AC.createBiquadFilter(),buf=AC.createBuffer(1,AC.sampleRate*3,AC.sampleRate),arr=buf.getChannelData(0);for(let i=0;i<arr.length;i++)arr[i]=Math.random()*2-1;n.buffer=buf;n.loop=true;f.type='lowpass';f.frequency.value=780;g.gain.value=.018;n.connect(f).connect(g).connect(master);n.start();const bird=()=>{if(!natureStarted)return;const o=AC.createOscillator(),gg=AC.createGain(),t=AC.currentTime;o.type='sine';o.frequency.setValueAtTime(1900+Math.random()*900,t);o.frequency.exponentialRampToValueAtTime(2900+Math.random()*700,t+.07);o.frequency.exponentialRampToValueAtTime(1600+Math.random()*400,t+.16);gg.gain.setValueAtTime(.0001,t);gg.gain.exponentialRampToValueAtTime(.015,t+.025);gg.gain.exponentialRampToValueAtTime(.0001,t+.18);o.connect(gg).connect(master);o.start(t);o.stop(t+.2);setTimeout(bird,2200+Math.random()*4600)};setTimeout(bird,1300)}
function deerSpatial(d){const local=d.root.position.clone().sub(C.position).applyQuaternion(C.quaternion.clone().invert()),dist=Math.max(1,local.length());return{pan:Math.max(-1,Math.min(1,local.x/Math.max(1,Math.hypot(local.x,local.z)))),volume:Math.max(.15,Math.min(.65,1-dist/90))}}
function deerVoice(d,type='snort',extra=1,delay=0){if(!d?.root?.visible)return;const s=deerSpatial(d);playCue(type,{volume:s.volume*extra,pan:s.pan,rate:.95+Math.random()*.1,delay})}

const MODEL_URL='https://cdn.jsdelivr.net/gh/Quaternius/TestGltfAssets@master/Deer/Deer.glb';
const loader=new GLTFLoader();let deerSource=null,modelReady=false;
const RIG_NAMES=['fl1.l','fl2.l','fl3.l','fl1.r','fl2.r','fl3.r','rl1.l','rl2.l','rl3.l','rl1.r','rl2.r','rl3.r','neck1','neck2','headctrl','thorax','pelvis'];
const modelPromise=loader.loadAsync(MODEL_URL).then(g=>{deerSource=g.scene;deerSource.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});modelReady=true;return deerSource});

const DEER=[],MIN_R=26,MAX_R=66,BAG_CAP=5;
function normalizeModel(m){m.rotation.y=Math.PI/2;m.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(m),s=new THREE.Vector3();b.getSize(s);m.scale.setScalar(2.65/Math.max(.001,s.y));m.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(m);const c=new THREE.Vector3();b.getCenter(c);m.position.x-=c.x;m.position.z-=c.z;m.position.y-=b.min.y;m.updateMatrixWorld(true)}
function captureRig(m){const rig={},base={};m.traverse(o=>{const n=(o.name||'').toLowerCase();if(RIG_NAMES.includes(n)){rig[n]=o;base[n]=o.rotation.clone()}});return{rig,base}}
function randomSpawn(){const a=Math.random()*Math.PI*2,r=31+Math.random()*27;return new THREE.Vector3(Math.cos(a)*r,0,Math.sin(a)*r)}
function spawnDeer(d,initial=false){const p=randomSpawn();d.root.position.set(p.x,ty(p.x,p.z),p.z);d.root.rotation.set(0,Math.random()*Math.PI*2,0);d.visual.rotation.set(0,0,0);d.visual.position.set(0,0,0);d.hp=100;d.state='wander';d.t=Math.random()*4;d.dir=Math.atan2(-p.z,-p.x)+(Math.random()-.5)*1.9;d.root.rotation.y=-d.dir+Math.PI/2;d.root.visible=true;d.respawn=0;d.hitKick=0}
function createDeer(index){const root=new THREE.Group(),visual=new THREE.Group();root.add(visual);S.add(root);const model=cloneSkeleton(deerSource);normalizeModel(model);visual.add(model);const {rig,base}=captureRig(model);const d={index,root,visual,model,rig,base,hp:100,state:'wander',t:Math.random()*5,dir:Math.random()*6.28,speed:.72+Math.random()*.38,respawn:0,hitKick:0,phase:Math.random()*6.28};spawnDeer(d,true);return d}
function setBone(d,n,a,v){const b=d.rig[n],r=d.base[n];if(b&&r)b.rotation[a]=r[a]+v}
function animateRig(d,now,running,idle){const f=running?10.8:idle?1.25:4.2,A=running?.68:idle?.04:.23,p=now*.001*f+d.phase,a=Math.sin(p)*A,b=-a;
 setBone(d,'fl1.l','x',a);setBone(d,'fl1.r','x',b);setBone(d,'rl1.l','x',b);setBone(d,'rl1.r','x',a);
 setBone(d,'fl2.l','x',Math.max(0,-a)*(running?.55:.35));setBone(d,'fl2.r','x',Math.max(0,-b)*(running?.55:.35));setBone(d,'rl2.l','x',Math.max(0,-b)*(running?.72:.48));setBone(d,'rl2.r','x',Math.max(0,-a)*(running?.72:.48));
 setBone(d,'fl3.l','x',-Math.max(0,a)*.28);setBone(d,'fl3.r','x',-Math.max(0,b)*.28);setBone(d,'rl3.l','x',-Math.max(0,b)*.32);setBone(d,'rl3.r','x',-Math.max(0,a)*.32);
 setBone(d,'neck1','z',Math.sin(p*.45)*(running?.055:idle?.035:.025));setBone(d,'headctrl','z',Math.sin(p*.32)*(idle?.12:running?.03:.055));setBone(d,'thorax','z',Math.sin(p*2)*(running?.035:.012));setBone(d,'pelvis','z',-Math.sin(p*2)*(running?.03:.01));
 d.visual.position.y=Math.abs(Math.sin(p))*(running?.055:idle?.003:.011);d.visual.rotation.x=-d.hitKick+Math.sin(p*2)*(running?.018:.006)}
function flee(d){if(!d.root.visible||d.state==='dead')return;d.state='run';d.t=0;d.dir=Math.atan2(d.root.position.z-C.position.z,d.root.position.x-C.position.x)+(Math.random()-.5)*.38;d.hitKick=.12}
function animateDeer(d,dt,now){if(!d.root.visible){d.respawn-=dt;if(d.respawn<=0)spawnDeer(d);return}d.t+=dt;d.hitKick=Math.max(0,d.hitKick-dt*1.7);if(d.state==='dead'){d.visual.rotation.z=THREE.MathUtils.lerp(d.visual.rotation.z,Math.PI*.47,1-Math.exp(-4.5*dt));d.respawn-=dt;if(d.respawn<=0){d.root.visible=false;d.respawn=1.5}return}
 const running=d.state==='run';let speed=running?5.8:d.speed;if(d.state==='wander'&&Math.random()<.0045)d.dir+=(Math.random()-.5)*1.0;
 const radius=Math.hypot(d.root.position.x,d.root.position.z);if(radius<MIN_R+2){d.dir=Math.atan2(d.root.position.z,d.root.position.x)+(Math.random()-.5)*.25;speed=Math.max(speed,1.5)}else if(radius>MAX_R){d.dir=Math.atan2(-d.root.position.z,-d.root.position.x)+(Math.random()-.5)*.5}
 d.root.position.x+=Math.cos(d.dir)*speed*dt;d.root.position.z+=Math.sin(d.dir)*speed*dt;d.root.position.y=ty(d.root.position.x,d.root.position.z);d.root.rotation.y=-d.dir+Math.PI/2;if(running&&d.t>4.2){d.state='wander';d.t=0}animateRig(d,now,running,false)}

const startBtn=$('#start');startBtn.disabled=true;startBtn.textContent='LOADING…';
Promise.all([modelPromise,audioPreload]).then(()=>{for(let i=0;i<6;i++)DEER.push(createDeer(i));startBtn.disabled=false;startBtn.textContent='START HUNT'}).catch(e=>{console.error(e);startBtn.textContent='RETRY';startBtn.disabled=false});

let run=false,shots=5,reloading=false,shotLock=false,totalShots=0,hits=0,yaw=0,pitch=0,tyaw=0,tpitch=0,recoil=0,last=performance.now(),shopOpen=false;const ray=new THREE.Raycaster();
const ui=()=>{const gun=SNIPERS[save.equipped];$('#ammo').textContent=shots;$('#reserve').textContent='∞';$('#score').textContent=save.kills;$('#coins').textContent=save.coins;$('#bag').textContent=`${save.bag}/${BAG_CAP}`;$('#gunName').textContent=gun.name;$('#acc').textContent=(totalShots?Math.round(hits/totalShots*100):100)+'%'};
function note(t,ms=800){const m=$('#msg');m.textContent=t;m.classList.add('show');clearTimeout(note.t);note.t=setTimeout(()=>m.classList.remove('show'),ms)}function pop(t,good=true){const e=$('#dmg');e.textContent=t;e.className='dmg show '+(good?'good':'');setTimeout(()=>e.classList.remove('show'),650)}
let bagBanner=document.createElement('div');bagBanner.className='bagFull';bagBanner.innerHTML='<b>BAG FULL · 5/5</b><span>Open SHOP and sell your deer to continue hunting</span>';document.body.appendChild(bagBanner);function showBagFull(){bagBanner.classList.add('show');$('#shopBtn').classList.add('attention');clearTimeout(showBagFull.t);showBagFull.t=setTimeout(()=>bagBanner.classList.remove('show'),4200)}function clearBagFull(){bagBanner.classList.remove('show');$('#shopBtn').classList.remove('attention')}
function deerProjectedRect(d){d.model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(d.model);if(box.isEmpty())return null;const min=box.min,max=box.max,corners=[];for(const x of[min.x,max.x])for(const y of[min.y,max.y])for(const z of[min.z,max.z])corners.push(new THREE.Vector3(x,y,z));let minX=99,maxX=-99,minY=99,maxY=-99,front=false;for(const p of corners){p.project(C);if(p.z>-1&&p.z<1)front=true;minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y)}return front?{minX,maxX,minY,maxY,box}:null}
function acquireTarget(){let best=null,bestScore=999;for(const d of DEER){if(!d.root.visible||d.state==='dead')continue;const r=deerProjectedRect(d);if(!r)continue;const margin=.028,inside=0>=r.minX-margin&&0<=r.maxX+margin&&0>=r.minY-margin&&0<=r.maxY+margin;if(!inside)continue;const cx=(r.minX+r.maxX)/2,cy=(r.minY+r.maxY)/2,dist=C.position.distanceTo(d.root.position),score=Math.hypot(cx,cy)+dist*.0002;if(score<bestScore){const rel=(0-r.minY)/Math.max(.001,r.maxY-r.minY);best={d,zone:rel>.72?'head':rel>.45?'vital':'body',dist};bestScore=score}}return best}
function shoot(){if(!run||shopOpen||reloading||shotLock)return;if(save.bag>=BAG_CAP){showBagFull();note('BAG FULL 5/5 · SELL BEFORE HUNTING MORE',1500);return}const gun=SNIPERS[save.equipped];if(shots<=0){note('MAG EMPTY · RELOAD',1000);return}initAudio().catch(()=>{});shots--;totalShots++;shotLock=true;recoil=.048*(1+gun.sway*.1);ui();playCue('shot',{volume:1,rate:.99+Math.random()*.02});setTimeout(()=>shotLock=false,gun.fireDelay*1000);const target=acquireTarget();if(!target){note('MISS',480);DEER.forEach(d=>{if(d.root.visible&&d.state!=='dead'&&d.root.position.distanceTo(C.position)<42)flee(d)});if(shots===0)setTimeout(()=>note('5 SHOTS USED · RELOAD',1200),520);return}
 hits++;const {d,zone}=target,base=zone==='head'?100:zone==='vital'?72:gun.damage,damage=Math.min(100,Math.round(base*(zone==='body'?1:1)));d.hp=Math.max(0,d.hp-damage);pop(zone==='head'?'HEADSHOT · -100':zone==='vital'?`VITAL · -${damage}`:`-${damage} DMG`);const sp=deerSpatial(d);playCue('impact',{volume:.95,pan:sp.pan,delay:.035});deerVoice(d,'grunt',1.1,.10);if(d.hp<=0){d.state='dead';d.t=0;d.respawn=2.4;save.kills++;save.bag=Math.min(BAG_CAP,save.bag+1);persist();note(`DEER DOWN · SCORE ${save.kills}`,1000);if(save.bag>=BAG_CAP)setTimeout(()=>{showBagFull();note('BAG FULL 5/5 · SELL TO CONTINUE',1800)},950)}else{flee(d);note(`${zone.toUpperCase()} HIT · ${d.hp} HP`,720)}DEER.forEach(o=>{if(o!==d&&o.root.visible&&o.state!=='dead'&&o.root.position.distanceTo(d.root.position)<16)flee(o)});if(shots===0)setTimeout(()=>note('5 SHOTS USED · RELOAD',1200),700);ui()}
function reload(){if(!run||shopOpen||reloading||shotLock)return;const gun=SNIPERS[save.equipped];if(shots>=5)return;initAudio().catch(()=>{});reloading=true;note('RELOADING 5-ROUND MAG…',Math.round(gun.reload*1000));playCue('reload',{volume:1});setTimeout(()=>{shots=5;reloading=false;ui();note('5/5 READY',500)},gun.reload*1000)}
function openShop(){shopOpen=true;run=false;renderShop();$('#shop').classList.add('open')}function closeShop(){shopOpen=false;run=true;$('#shop').classList.remove('open')}
function renderShop(){const list=$('#rifles');list.innerHTML='';SNIPERS.forEach(g=>{const owned=save.owned.includes(g.id),equipped=save.equipped===g.id,card=document.createElement('button');card.className='rifle '+(equipped?'equipped':'');card.innerHTML=`<div><strong>${g.name}</strong><small>${g.desc}</small><em>DMG ${g.damage} · MAG 5 · ${g.scope}× · STABILITY ${Math.round(100/g.sway)}%</em></div><span>${equipped?'EQUIPPED':owned?'EQUIP':g.price+' 🪙'}</span>`;card.onclick=()=>{if(equipped)return;if(!owned){if(save.coins<g.price){note('NOT ENOUGH COINS');return}save.coins-=g.price;save.owned.push(g.id)}save.equipped=g.id;shots=5;persist();renderShop();ui()};list.appendChild(card)});$('#sellCount').textContent=save.bag;$('#sellValue').textContent=save.bag*90}
$('#sell').onclick=()=>{if(save.bag<=0)return;save.coins+=save.bag*90;save.bag=0;persist();clearBagFull();renderShop();ui();note('DEER SOLD · HUNTING UNLOCKED',1100)};$('#shopBtn').onclick=openShop;$('#closeShop').onclick=closeShop;$('#fire').onpointerdown=e=>{e.preventDefault();shoot()};$('#reload').onpointerdown=e=>{e.preventDefault();reload()};
startBtn.onclick=async()=>{if(!modelReady){location.reload();return}startBtn.disabled=true;startBtn.textContent='STARTING…';try{await initAudio()}catch(e){console.warn('audio fallback',e)}$('#intro').style.display='none';run=true;ui();if(save.bag>=BAG_CAP)setTimeout(showBagFull,500)};
let drag=false,lx=0,ly=0;addEventListener('pointerdown',e=>{if(!run||shopOpen||e.target.closest?.('button'))return;drag=true;lx=e.clientX;ly=e.clientY});addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;const gun=SNIPERS[save.equipped],sens=.00185*(6/gun.scope);tyaw-=dx*sens;tpitch=Math.max(-.62,Math.min(.62,tpitch-dy*sens))});addEventListener('pointerup',()=>drag=false);addEventListener('pointercancel',()=>drag=false);
function loop(now){requestAnimationFrame(loop);const dt=Math.min(.033,(now-last)/1000);last=now;if(modelReady)DEER.forEach(d=>animateDeer(d,dt,now));const gun=SNIPERS[save.equipped],sway=(run?gun.sway:0),t=now*.001;yaw=THREE.MathUtils.lerp(yaw,tyaw,1-Math.exp(-16*dt));pitch=THREE.MathUtils.lerp(pitch,tpitch,1-Math.exp(-16*dt));recoil=THREE.MathUtils.lerp(recoil,0,1-Math.exp(-15*dt));C.rotation.y=yaw+Math.sin(t*1.2)*.00105*sway;C.rotation.x=pitch+Math.sin(t*.92)*.00076*sway+recoil;C.fov=105/gun.scope;C.updateProjectionMatrix();let nearest=999;DEER.forEach(d=>{if(d.root.visible&&d.state!=='dead')nearest=Math.min(nearest,C.position.distanceTo(d.root.position))});$('#range').textContent=(nearest<998?Math.round(nearest):'--')+' m';if(run&&audioBuffer&&now>=nextDeerCall){const live=DEER.filter(d=>d.root.visible&&d.state!=='dead');if(live.length){const d=live[Math.floor(Math.random()*live.length)];deerVoice(d,Math.random()<.58?'snort':'grunt',.9)}nextDeerCall=now+4800+Math.random()*6500}R.render(S,C)}requestAnimationFrame(loop);
addEventListener('resize',()=>{R.setSize(innerWidth,innerHeight,false);C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix()});
window.__forestStalker={version:'5.4',state:()=>({kills:save.kills,bag:save.bag,coins:save.coins,alive:DEER.filter(d=>d.root.visible&&d.state!=='dead').length,model:'Quaternius Deer GLB',audioReady:!!audioBuffer,minDeerDistance:MIN_R,magazine:5}),deer:DEER,acquireTarget};
ui();
